language: python
python:
  - "2.7"
  - "3.5"
install:
    - pip install --upgrade pip setuptools wheel
    - pip install --only-binary=numpy,scipy
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
script:
    - python -m unittest discover tests
    - flake8
