language: python
python:
  - "3.6"
install:
    - pip install --upgrade pip setuptools wheel
    - pip install --only-binary=numpy numpy
    - pip install --only-binary=scipy scipy
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
script:
    - coverage run -m py.test tests
    - flake8
after_success:
    - bash <(curl -s https://codecov.io/bash)

